-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoYhdZxpBduQYYyw9vqJ5wNEcl38JAiRWQyIIYqql1lmgCgYIKoZIzj0DAQehRANCAAR9LOMlHKlLnBJysQMIabbFoDzaJzwVwsZHJGRzA7gj8NthCco7Kxn7ibFL3EBoWxfQ6gJvSnoVpElhvla7sEiG
-----END PRIVATE KEY-----